import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
	title: "JEFI",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className="h-screen bg-slate-100 antialiased">
				{children}
			</body>
		</html>
	);
}
